"""Add role to participants

Revision ID: 926a606190bc
Revises: c5e44a9d9031
Create Date: 2025-05-30 09:50:40.541493+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "926a606190bc"
down_revision: Union[str, None] = "c5e44a9d9031"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("HOST", "MEMBER", name="role").create(op.get_bind())
    op.add_column(
        "participation",
        sa.Column(
            "role",
            postgresql.ENUM("HOST", "MEMBER", name="role", create_type=False),
            nullable=False,
            server_default="MEMBER",
        ),
    )
    op.alter_column("participation", "role", server_default=None)
    op.create_unique_constraint(
        "uq_meeting_user", "participation", ["meeting_id", "user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_meeting_user", "participation", type_="unique")
    op.drop_column("participation", "role")
    sa.Enum("HOST", "MEMBER", name="role").drop(op.get_bind())
    # ### end Alembic commands ###
