"""Add simulated to partcipants

Revision ID: d579feca9eb6
Revises: 926a606190bc
Create Date: 2025-05-31 03:43:56.940282+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d579feca9eb6"
down_revision: Union[str, None] = "926a606190bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participation",
        sa.Column(
            "simulated", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participation", "simulated")
    # ### end Alembic commands ###
